import { FaFacebook, FaInstagramSquare, FaTiktok } from "react-icons/fa";

export const repertorio = [
  { id: 1, title: "A pesar de todo", artist: "Alejandro Fernández" },
  { id: 2, title: "A una señora", artist: "Alejandro Fernández" },
  { id: 3, title: "Abrázame", artist: "Alejandro Fernández" },
  { id: 4, title: "Acá entre nos", artist: "Vicente Fernández" },
  { id: 5, title: "Alejandra", artist: "Desconocido" },
  { id: 6, title: "Amor de los dos", artist: "Vicente Fernández" },
  { id: 7, title: "Amor perdido", artist: "Javier Solís" },
  { id: 8, title: "Amorcito corazón", artist: "Pedro Infante" },
  { id: 9, title: "Así como soy yo soy", artist: "Alejandro Fernández" },
  { id: 10, title: "Aunque no sea conmigo", artist: "Bunbury" },
  { id: 11, title: "Avísame", artist: "Alejandro Fernández" },
  { id: 12, title: "Ay amor", artist: "Alejandro Fernández" },
  { id: 13, title: "Besame mucho", artist: "Balada" },
  { id: 14, title: "Bonita", artist: "Javier Solís" },
  { id: 15, title: "Caballero", artist: "Alejandro Fernández" },
  { id: 16, title: "Caminos de Michoacan", artist: "Dominio Popular" },
  { id: 17, title: "Cascos ligeros", artist: "Alejandro Fernández" },
  { id: 18, title: "Cataclismo", artist: "Javier Solís" },
  { id: 19, title: "Cenizas", artist: "Javier Solís" },
  { id: 20, title: "Cien años", artist: "Pedro Infante" },
  { id: 21, title: "Como fue", artist: "Beny More" },
  { id: 22, title: "Como puede ser", artist: "Alejandro Fernández" },
  {
    id: 23,
    title: "Como quien pierde una estrella",
    artist: "Alejandro Fernández",
  },
  { id: 24, title: "Concavo y Convexo", artist: "Alejandro Fernández" },
  { id: 25, title: "Corazón partío", artist: "Alejandro Sanz" },
  { id: 26, title: "Cruz de olvido", artist: "Vicente Fernández" },
  {
    id: 27,
    title: "Cuando yo queria ser grande",
    artist: "Alejandro Fernández",
  },
  { id: 28, title: "Cuatro cirios", artist: "Javier Solís" },
  { id: 29, title: "Cucurrucucú Paloma", artist: "Pedro Infante" },
  { id: 30, title: "De que manera te olvido", artist: "Vicente Fernández" },
  { id: 31, title: "Dentro de mi corazón", artist: "Alejandro Fernández" },
  { id: 32, title: "Desahogo", artist: "Roberto Carlos" },
  { id: 33, title: "Donde vas tan sola", artist: "Alejandro Fernández" },
  { id: 34, title: "Durmiendo con a Luna", artist: "Reily Barba" },
  { id: 35, title: "Echame a mi la culpa", artist: "Javier Solís" },
  { id: 36, title: "El Mariachi", artist: "Antonio Banderas" },
  { id: 37, title: "El Rey", artist: "José Alfredo Jiménez" },
  { id: 38, title: "El Loco", artist: "Javier Solís" },
  { id: 39, title: "El siete mares", artist: "José Alfredo Jiménez" },
  { id: 40, title: "El Triste", artist: "José José" },
  { id: 41, title: "Ella", artist: "José Alfredo Jiménez" },
  { id: 42, title: "Embrujo", artist: "Andrés Cepeda" },
  { id: 43, title: "En tu pelo", artist: "Javier Solís" },
  { id: 44, title: "Encadenados", artist: "Alejandro Fernández" },
  { id: 45, title: "Entrega total", artist: "Javier Solís" },
  { id: 46, title: "Es cosa de hombres", artist: "Alejandro Fernández" },
  { id: 47, title: "Esclavo y amo", artist: "Javier Solís" },
  { id: 48, title: "Estos celos", artist: "Vicente Fernández" },
  { id: 49, title: "Estuve", artist: "Alejandro Fernández" },
  { id: 50, title: "Gema", artist: "Javier Solís" },
  { id: 51, title: "Granada", artist: "Javier Solís" },
  { id: 52, title: "Hermoso cariño", artist: "Vicente Fernández" },
  { id: 53, title: "Hoy tengo ganas de ti", artist: "Alejandro Fernández" },
  { id: 54, title: "Il mondo", artist: "Jimmy Fontana" },
  { id: 55, title: "Ingrato amor", artist: "Alejandro Fernández" },
  { id: 56, title: "Intenta vivir sin mí", artist: "Alejandro Fernández" },
  { id: 57, title: "Jamás te vi tan linda", artist: "Alejandro Fernández" },
  { id: 58, title: "Juan Charrasqueado", artist: "Jorge Negrete" },
  { id: 59, title: "Lástima que seas ajena", artist: "Vicente Fernández" },
  { id: 60, title: "Las llaves de mi alma", artist: "Vicente Fernández" },
  { id: 61, title: "La mitad que me faltaba", artist: "Alejandro Fernández" },
  { id: 62, title: "Llorando penas", artist: "Alejandro Fernández" },
  { id: 63, title: "La mano de Dios", artist: "José Alfredo Jiménez" },
  { id: 64, title: "La mujer ideal", artist: "Alejandro Fernández" },
  { id: 65, title: "La tertulia", artist: "Pedro Infante" },
  { id: 66, title: "La verdolaga", artist: "Pedro Infante" },
  { id: 67, title: "Las rejas no matan", artist: "Javier Solís" },
  { id: 68, title: "Llorarás llorarás", artist: "Javier Solís" },
  { id: 69, title: "Loco", artist: "Alejandro Fernández" },
  { id: 70, title: "L.O.V.E.", artist: "Frank Sinatra" },
  { id: 71, title: "Las mañanitas", artist: "Javier Solís" },
  { id: 72, title: "Mátalas", artist: "Alejandro Fernández" },
  { id: 73, title: "Me dediqué a perderte", artist: "Alejandro Fernández" },
  { id: 74, title: "Mentira, mentira", artist: "Javier Solís" },
  { id: 75, title: "Mentirosos", artist: "Alejandro Fernández" },
  { id: 76, title: "México lindo y querido", artist: "Javier Solís" },
  { id: 77, title: "Me voy", artist: "Andrés Cepeda" },
  { id: 78, title: "Me voy a quitar de en medio", artist: "Vicente Fernández" },
  { id: 79, title: "Mi viejo", artist: "Vicente Fernández" },
  { id: 80, title: "Mitad tú, mitad yo", artist: "Alejandro Fernández" },
  { id: 81, title: "Moño negro", artist: "Alejandro Fernández" },
  { id: 82, title: "Mujer", artist: "Alejandro Fernández" },
  { id: 83, title: "Mujeres divinas", artist: "Vicente Fernández" },
  { id: 84, title: "My way", artist: "Frank Sinatra" },
  { id: 85, title: "Nana Pancha", artist: "Pedro Infante" },
  { id: 86, title: "Niña amada mía", artist: "Alejandro Fernández" },
  { id: 87, title: "No lo beses", artist: "Alejandro Fernández" },
  { id: 88, title: "No", artist: "Alejandro Fernández" },
  { id: 89, title: "No volveré", artist: "Pedro Infante" },
  { id: 90, title: "Nube viajera", artist: "Alejandro Fernández" },
  { id: 91, title: "Ojitos traidores", artist: "Javier Solís" },
  { id: 92, title: "Ojo por ojo", artist: "Alejandro Fernández" },
  { id: 93, title: "Otra vida", artist: "Alejandro Fernández" },
  { id: 94, title: "Paloma querida", artist: "José Alfredo Jiménez" },
  { id: 95, title: "Para siempre", artist: "Vicente Fernández" },
  { id: 96, title: "Perfume de gardenias", artist: "Javier Solís" },
  { id: 97, title: "Piel de niña", artist: "Alejandro Fernández" },
  {
    id: 98,
    title: "Popurrí Alejandro Fernández",
    artist: "Alejandro Fernández",
  },
  { id: 99, title: "Popurrí Juan Gabriel", artist: "Alejandro Fernández" },
  { id: 100, title: "Por tu maldito amor", artist: "Vicente Fernández" },
  { id: 101, title: "Procuro olvidarte", artist: "Alejandro Fernández" },
  { id: 102, title: "Qué bonita es mi tierra", artist: "Javier Solís" },
  { id: 103, title: "Qué bonito amor", artist: "José Alfredo Jiménez" },
  { id: 104, title: "Qué bueno", artist: "Alejandro Fernández" },
  { id: 105, title: "Qué digan misa", artist: "Alejandro Fernández" },
  { id: 106, title: "Qué lástima", artist: "Alejandro Fernández" },
  { id: 107, title: "Qué poca", artist: "Alejandro Fernández" },
  { id: 108, title: "Qué seas muy feliz", artist: "Alejandro Fernández" },
  { id: 109, title: "Regálame esta noche", artist: "Javier Solís" },
  { id: 110, title: "Reloj", artist: "Javier Solís" },
  { id: 111, title: "Renunciación", artist: "Javier Solís" },
  { id: 112, title: "Retirada", artist: "Javier Solís" },
  { id: 113, title: "Sabor a mí", artist: "Javier Solís" },
  { id: 114, title: "Sabrás que te quiero", artist: "Javier Solís" },
  { id: 115, title: "Se me va la voz", artist: "Alejandro Fernández" },
  { id: 116, title: "Se te olvida", artist: "Javier Solís" },
  { id: 117, title: "Serenata Huasteca", artist: "Pedro Infante" },
  { id: 118, title: "Si he sabido amor", artist: "Alejandro Fernández" },
  { id: 119, title: "Si Dios me quita la vida", artist: "Javier Solís" },
  { id: 120, title: "Si nos dejan", artist: "José Alfredo Jiménez" },
  { id: 121, title: "Si tú no vuelves", artist: "Alejandro Fernández" },
  { id: 122, title: "Sombras", artist: "Javier Solís" },
  { id: 123, title: "Te olvidé", artist: "Alejandro Fernández" },
  { id: 124, title: "Te quedas o te vas", artist: "Alejandro Fernández" },
  { id: 125, title: "Todo", artist: "Alejandro Fernández" },
  { id: 126, title: "Tu recuerdo y yo", artist: "José Alfredo Jiménez" },
  { id: 127, title: "Tú regresarás", artist: "Alejandro Fernández" },
  { id: 128, title: "Tú y las nubes", artist: "José Alfredo Jiménez" },
  { id: 129, title: "Tú solo tú", artist: "José Alfredo Jiménez" },
  { id: 130, title: "Urge", artist: "Vicente Fernández" },
  { id: 131, title: "Vamos a darnos tiempo", artist: "Alejandro Fernández" },
  { id: 132, title: "Volver, volver", artist: "Vicente Fernández" },
  { id: 133, title: "Voy", artist: "Alejandro Fernández" },
];
